# Generated by Django 2.0.5 on 2018-05-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='about_second',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
