# Generated by Django 2.0.5 on 2018-05-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_api', '0002_data_about_second'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='about_second',
        ),
        migrations.AddField(
            model_name='data',
            name='average_mark',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
