# Generated by Django 2.0.5 on 2018-05-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_api', '0003_auto_20180516_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='about',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='data',
            name='comments',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
