# Generated by Django 2.0.5 on 2018-05-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_api', '0004_auto_20180517_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='first_video',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
