# Generated by Django 2.0.5 on 2018-05-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_api', '0005_data_first_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='first_video',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
