# Generated by Django 2.0.5 on 2018-05-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse_api', '0007_auto_20180524_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='first_video',
        ),
    ]
