# Generated by Django 2.0.5 on 2018-05-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_api', '0008_remove_data_first_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='youtube',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
