# Generated by Django 2.0.5 on 2018-05-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_api', '0009_auto_20180524_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='first_video',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
